### ISSUE TITLE
Oddaja projektne naloge

### ISSUE THREAD

**Issue by janezpod** [janezpod/APPR-2021-22#1]
Pozdravljeni!

Projekt oddajam v ocenjevanje.
Program ob prvem zagonu prenese podatke z Amazon Web Service. Prenos traja kar nekaj časa, saj so podatki o kolesarskih vožnjah skupaj veliki cca. 4 Gb.

Lep pozdrav,
Janez Podlogar

**Comment by katarinabrilej** [comment]
Hvala, bomo ocenili.

Lep pozdrav,
Katarina

**Comment by M4rble** [comment]
Zdravo,

projekt zadošča za pozitivno oceno, trenutno število točk je 76. Če želiš višjo oceno lahko projekt še vedno popraviš oziroma dodaš nekaj stvari:
- pri napredni analizi lahko dodaš razvrščanje v skupine (clustering). Za napotke kako to izvesti si oglej profesorjeve zvezke z zapiski predavanj oziroma skripte iz vaj
- pri napovedni analizi lahko dodaš izbiranje modela s prečnim preverjanjem (ponovno glej profesorjeve zvezke), ter na koncu dejanski graf napovedi vrednosti za izbrani model (model si samo izbral, nič pa nisi z njim napovedal, oziroma napovedi nisi prikazal v poročilu)
- dodaš lahko Shiny aplikacijo

Lep pozdrav,
Anže Mramor

**Comment by janezpod** [comment]
Zdravo,

dodal sem izbiro modela s prečnim preverjanjem.
Bo to dovolj?

lp, Janez

**Comment by katarinabrilej** [comment]
Dobro bi bilo dodati tudi clustering (hierarhično združevanje in kmeans, izbira optimalnega števila skupin z obrisi/koleni, primerjava dobljenih skupin na podlagi obeh algoritmov). 

LP, Katarina

**Comment by janezpod** [comment]
Dodal sem razvrščanje vremena v skupine. Narisal sem dendrogram in izrisal kolena, poiskal optimalni k z hierhičnim združevanjem in z metodo k-tih voditeljev ter izrisal dobljeno razbitje množice.

lp, Janez

**Comment by katarinabrilej** [comment]
Sem vnesla oceno v spletno učilnico, pri vizualizaciji dobiš še dodatnih 5 točk, tako da je končna ocena 10 (94 točk).

Lep pozdrav, Katarina
